packages:
  - 'packages/*'
  - 'examples'

catalogs:
  core:
    typescript: ^5.8.3
    '@typescript-eslint/parser': ^8.33.1
    '@typescript-eslint/utils': ^8.33.1
  lint:
    eslint: 9.28.0
    '@eslint/js': ^9.28.0
    typescript-eslint: ^8.33.1
  fmt:
    prettier: 4.0.0-alpha.12
  test:
    vitest: ^3.2.2
    '@typescript-eslint/rule-tester': ^8.33.1
  build:
    tsdown: ^0.12.7
  others:
    '@types/node': ^22.15.30
    nx: ^21.1.2
